MODEL:
  META_ARCHITECTURE: "OvMlr"
  WEIGHTS: "models/resnet50_miil_21k.pkl"
  BACKBONE:
    NAME: build_p67_timm_fpn_backbone
  TIMM:
    BASE_NAME: resnet50_in21k
  FPN:
    IN_FEATURES: ["layer3", "layer4", "layer5"]
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
    USE_SIGMOID_CE: True
    USE_ZEROSHOT_CLS: True
    ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/coco_clip_a+cname.npy'
    IGNORE_ZERO_CATS: True
    CAT_FREQ_PATH: 'datasets/coco/zero-shot/instances_train2017_seen_2_oriorder_cat_info.json'

DATASETS:
  TRAIN: ("coco_zeroshot_train_oriorder", "coco_caption_train_tags")
  TEST: ("coco_generalized_zeroshot_val",)
SOLVER:
  MAX_ITER: 180000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  IMS_PER_BATCH: 16
  BASE_LR: 0.00005
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.001
  OPTIMIZER: "ADAMW"
  USE_CUSTOM_SOLVER: True
  CHECKPOINT_PERIOD: 10000
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: RandomResizedCrop
  TRAIN_SIZE: 480
MLR:
  NORMED_EMBEDDING: True
  ENABLE_MLR: True
  ENABLE_IMAGE_KD: True
  EMBEDDING_PATH: "resources/coco_there_is_a_cls_vitb32.pt"
  MLR_LOSS_WEIGHT: 1.0
  LOGIT_SCALE: 20.0
  CLIP_VERSION: "ViT-B/32"
  DATASET: "COCO"
  GLOBAL_DIM: 1280
  NUM_CLASSES: 80
  CLIP_IE_INFERENCE: True
  LAMBDA_NOVEL: 0.5
  LAMBDA_BASE: 0.8
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [1, 1]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [4, 4]
  DATASET_INPUT_SIZE: [480, 480]
  USE_RFS: [True, False]
  DATASET_INPUT_SCALE: [[0.5], [0.5]]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: ['box', 'image']
  NUM_WORKERS: 8
WITH_IMAGE_LABELS: True
VERSION: 2
FP16: True