MODEL:
  META_ARCHITECTURE: "OvMlr"
  MASK_ON: False
  WEIGHTS: "models/resnet50_miil_21k.pkl"
  BACKBONE:
    NAME: build_p67_timm_fpn_backbone
  TIMM:
    BASE_NAME: resnet50_in21k
  FPN:
    IN_FEATURES: ["layer3", "layer4", "layer5"]
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  ROI_HEADS:
    NUM_CLASSES: 1203
DATASETS:
  TRAIN: ("lvis_v1_train_norare", "imagenet_lvis_v1")
  TEST: ("lvis_v1_val",)
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [1, 4]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [16, 64]
  DATASET_INPUT_SIZE: [480, 320]
  USE_RFS: [True, False]
  DATASET_INPUT_SCALE: [[0.7], [0.8]]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: ['box', 'image']
  NUM_WORKERS: 8
TEST:
  DETECTIONS_PER_IMAGE: 300
SOLVER:
  CHECKPOINT_PERIOD: 5000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  WARMUP_ITERS: 10000
  WARMUP_FACTOR: 0.00001
  USE_CUSTOM_SOLVER: True
  OPTIMIZER: "ADAMW"
  MAX_ITER: 180000
  IMS_PER_BATCH: 64
  BASE_LR: 0.0002
  CLIP_GRADIENTS:
    ENABLED: True
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: RandomResizedCrop
  TRAIN_SIZE: 480
VERSION: 2
FP16: True
WITH_IMAGE_LABELS: True
MLR:
  NORMED_EMBEDDING: True
  ENABLE_MLR: True
  ENABLE_IMAGE_KD: True
  EMBEDDING_PATH: "resources/lvis_there_is_a_cls_vitb32.pt"
  MLR_LOSS_WEIGHT: 1.0
  LOGIT_SCALE: 50.0
  CLIP_VERSION: "ViT-B/32"
  CLIP_IMG_SIZE: 224
  GLOBAL_DIM: 1280
  CLIP_IE_INFERENCE: True
